use_frameworks!

target 'Example' do
  pod 'Mindbox', :path => '../'
  pod 'MindboxLogger', :path => '../'
end

target 'MindboxNotificationServiceExtension' do
   pod 'MindboxNotifications', :path => '../'
   pod 'MindboxLogger', :path => '../'
end

target 'MindboxNotificationContentExtension' do
   pod 'MindboxNotifications', :path => '../'
   pod 'MindboxLogger', :path => '../'
end
