name: SDK CI

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!release-*'
    paths-ignore:
      - '**.md'
    tags-ignore:
      - '**'
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cirruslabs/swiftlint-action@v1
      with:
        args: --config .swiftlint.yml

  build:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Update bundler
      run: gem install bundler
    - name: Install bundler dependencies
      run: bundle install
#    - name: Install yeetd
#      run: |
#          wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
#          sudo installer -pkg yeetd-normal.pkg -target /
#          yeetd &

    - name: Update Fastlane
      run: bundle update fastlane

#    - name: Check Fastlane scan parameters
#      run: bundle exec fastlane action scan

#    - name: List available simulators
#      run: xcrun simctl list
#
#    - name: Boot simulator
#      run: xcrun simctl boot "iPhone SE (3rd generation)"
#
#    - name: Shutdown simulator
#      run: xcrun simctl shutdown all

#    - name: Shutdown all simulators
#      run: xcrun simctl shutdown all
#
#    - name: Erase all simulators
#      run: xcrun simctl erase all

    - name: Check CPU usage
      run: top -l 1 -s 0 | grep "CPU usage"
    - name: Check memory usage
      run: top -l 1 -s 0 | grep PhysMem
    - name: Check available disk space
      run: df -h

    - name: Check simctl list
      run: xcrun simctl list

#    - name: Run unit tests
#      run: bundle exec fastlane unitTestLane


    - name: Run unit tests directly
      run: |
        set -o pipefail && xcodebuild test \
          -project Mindbox.xcodeproj \
          -scheme Mindbox \
          -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=18.1' \
          -only-testing:MindboxTests \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty
